### ISSUE TITLE
Channel layout changed (missing Playlists) 

### ISSUE THREAD

**Issue by TheColdOne** [yuliskov/SmartTube#3066]
Beta 20.15

Just today I am seeing the Channel view changed. It goes (in rows); Videos, Shorts, Live, Playlists

When before it was Videos and then Playlists organized in groups (as set by the channel itself).

In the new layout, the Playlist row stops short, so the full list of Playlists isn't accessible.

I'm not sure if this is due to a YouTube change or if this was in the most recent change (though the only change list item was live video starting at the beginning fix and latest videos fix).

**Comment by Maeldor** [comment]
Can confirm this behaviour has occurred somewhere between 20.09 and 20.16. I just updated from the former to the latter and it's now messed up.

It's also missing the Open Playlist item in the context menu for many rows, such as Videos, which I found useful to view a larger grid of the channel's videos (because the row view isn't very useful with how limited the amount you can see at once). Would be really nice to get this menu item back in these places. Thanks!

**Comment by TheColdOne** [comment]
@Maeldor can you check the latest beta? I updated to 20.20 and it looks like the Playlist rows are back if you scroll down past the new rows.

**Comment by TheColdOne** [comment]
Issue still persists in 20.36.

**Comment by TheColdOne** [comment]
Issue still persists in 20.52. 

The "Playlists" row will load content when you scroll to the end, but if you are scrolling a custom row/list of Playlists then they won't load more than the initial view.

**Comment by TheColdOne** [comment]
Closing in favor of new issue: https://github.com/yuliskov/SmartTube/issues/3206

Evolution of the same problem, but more specific now (less broad of issue in channel page)
