### ISSUE TITLE
21.34:  Back to errors again.

### ISSUE THREAD

**Issue by thoots99** [yuliskov/SmartTube#3316]
Updated to 21.34, after having quite a nice time without any error messages whatsoever over the past few updates.  Now it's back to just a bunch of different error messages, usually at the beginning of videos.  "I've seen it far worse" in the past, but I get at least a few error messages every day, since I installed 21.34.

**Comment by thoots99** [comment]
Not completed, issue ignored.  Will try again with several dozen error message examples.

**Comment by Cainama** [comment]
Please, understand what an issue is. Educate yourself as an user instead of
crying about something that developers aren't able to understand.

First, identify the problem.
Second, specify the steps required to make the problem pop up.
Third, provide any information that could be useful about the environment,
i.e. your device's model, Android version, if you were connected to WiFi or
LTE, if you were using VPN...

Any request not taking this into account can't be reproduced, and so
developers aren't able to trace the problem and fix it.

Developers aren't here to make your dreams true, they are here to help. At
the very least, the minimum we can do as users is provide enough feedback
to improve the app.

**Comment by thoots99** [comment]
Cainama,

Yes, that's why I closed the issue I started -- I hadn't included any information about my issues, So, I figured it was just best to close the issue as a "housecleaning" effort.  That said, I presume the developers are aware that most of the common error messages are "Unknown error null" and "Unknown error Invalid integer size" with some value or another.  And so on.  My original message was just intended to be a quick note that I was starting to get these kinds of things, after several releases when I rarely saw any error messages whatsoever.  I'll definitely include detailed error messages when I open a new issue in the future.
